version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/libri-gmbh/kube-vault

    steps:
      - checkout
      - run:
          name: install dependencies
          command: go mod download

      - run:
          name: run tests
          command: go test -v ./...

  lint:
    docker:
      - image: golangci/golangci-lint:v1.24.0
    working_directory: /go/src/github.com/libri-gmbh/kube-vault

    steps:
      - checkout
      - run:
          name: Golang CI Lint
          command: golangci-lint run -v

  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/libri-gmbh/kube-vault

    steps:
      - checkout
      - setup_remote_docker
      - deploy:
          name: push docker images
          command: |
            [ "${CIRCLE_BRANCH}" != "master" ] && [ -z "${CIRCLE_TAG}" ] && exit 0
            export DOCKER_REPO=$(echo "${DOCKER_REPO_OWNER}/${CIRCLE_PROJECT_REPONAME}" | awk '{print tolower($0)}')
            docker login -u ${DOCKER_USER} -p "${DOCKER_PASS}" https://index.docker.io/v1/
            docker build -t ${DOCKER_REPO} .
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push ${DOCKER_REPO}
            fi
            if [ -n "${CIRCLE_TAG}" ]; then
              docker tag ${DOCKER_REPO} ${DOCKER_REPO}:${CIRCLE_TAG}
              docker push ${DOCKER_REPO}:${CIRCLE_TAG}
            fi

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test
      - build:
          requires:
            - lint
            - test
          context: docker
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
